#通用配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml         #SQL XML file address
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true
    # If the query result contains MathTool null column, MyBatis will not map this column during mapping
    call-setters-on-nulls: true
  global-config:
    banner: true
    #IGNORED:" ignore judgment "NOT_NULL:" Non-null judgment ") NOT_EMPTY:" Non-null judgment"
    field-strategy: NOT_EMPTY
    db-config:
      #Primary key type AUTO:" database ID increment "INPUT:" user INPUT ID",ID_WORKER:" globally unique ID (numeric type unique ID)", UUID:" globally unique ID UUID";
      id-type: INPUT



spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  task:
    scheduling:
      pool:
        size: 3            # 线程池核心线程数
        max-size: 3        # 线程池最大线程数
        keep-alive: 30s     # 线程池空闲线程存活时间
        queue-capacity: 3
      thread-name-prefix: "btlv-"  # 线程名称前缀
      await-termination: true    # 是否等待任务完成
      await-termination-period: 60s   # 等待任务完成的超时时间
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 6MB
  profiles:
    active: test

sa-token:
  # jwt??
  jwt-secret-key: hkdsajdlkhsdjslkdjashdmbfhck
  # token名称 (同时也是cookie名称)
  token-name: authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 21600
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  is-read-head: true
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: tik
  # 是否输出操作日志
  is-log: false

#swagger
swagger:
  enable: true

chainId: "56"
contract: "0x4Ffb718862757eDa8e2Ca5542E80779b6b12CD31"
pair: "0xc912826f2af862b4f60a44bb8042624ceb3146c2"
batchTransferERC20: "0x03C84f150F2baFBd972Aa26A5F470CD8C29c8044"
node: "0x4A1ABae3EbfF2a7561F898deD36F7402c9428fED"
market: "0x4bC774896b5C166a9b755E43056C60cA37313bCD"

