server:
  encoding:
    charset: UTF-8
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://43.247.134.121:3306/btlv?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&useSSL=false&failOverReadOnly=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: btlv
    password: c8K5wPNG64J87BtD
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: 43.247.134.121
    port: 6379
    username:
    password: testRedisMeTa@12#abC
    timeout: 5000
    lettuce:
      shutdown-timeout: 5000
      pool:
        enabled: true
        max-active: 100   #连接池最大连接数(使用负值表示没有限制)
        max-idle: 100      #连接池中的最大空闲连接
        min-idle: 10        #连接池中的最小空闲连接
        max-wait: 5s       #连接池最大阻塞等待时间(使用负值表示没有限制)
        time-between-eviction-runs: 1   #空闲对象逐出器线程的运行间隔时间。当为正值时，空闲对象逐出器线程启动，否则不执行空闲对象逐出。

